# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDemoblaze():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_order(self):
    # Test name: Order
    # Step # | name | target | value
    # 1 | open | https://www.demoblaze.com/ | 
    self.driver.get("https://www.demoblaze.com/")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | id=cartur | 
    self.driver.find_element(By.ID, "cartur").click()
    # 4 | click | css=.btn-success | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    # 5 | mouseOver | css=.btn-success | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-success")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOut | css=.btn-success | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 8 | type | id=name | adam
    self.driver.find_element(By.ID, "name").send_keys("adam")
    # 9 | type | id=country | tunisa
    self.driver.find_element(By.ID, "country").send_keys("tunisa")
    # 10 | click | id=city | 
    self.driver.find_element(By.ID, "city").click()
    # 11 | type | id=city | sousse
    self.driver.find_element(By.ID, "city").send_keys("sousse")
    # 12 | click | id=card | 
    self.driver.find_element(By.ID, "card").click()
    # 13 | type | id=card | 123456789
    self.driver.find_element(By.ID, "card").send_keys("123456789")
    # 14 | click | css=#orderModal form | 
    self.driver.find_element(By.CSS_SELECTOR, "#orderModal form").click()
    # 15 | click | id=month | 
    self.driver.find_element(By.ID, "month").click()
    # 16 | type | id=month | 12
    self.driver.find_element(By.ID, "month").send_keys("12")
    # 17 | click | id=year | 
    self.driver.find_element(By.ID, "year").click()
    # 18 | type | id=year | 2024
    self.driver.find_element(By.ID, "year").send_keys("2024")
    # 19 | click | css=#orderModal .btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, "#orderModal .btn-primary").click()
    # 20 | click | css=.confirm | 
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
  
  def test_addProduct(self):
    # Test name: addProduct
    # Step # | name | target | value
    # 1 | open | https://www.demoblaze.com/ | 
    self.driver.get("https://www.demoblaze.com/")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | css=.col-lg-4:nth-child(4) .card-img-top | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-4:nth-child(4) .card-img-top").click()
    # 4 | click | linkText=Add to cart | 
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    # 5 | assertAlert | Product added | 
    assert self.driver.switch_to.alert.text == "Product added"
  
  def test_categories(self):
    # Test name: categories
    # Step # | name | target | value
    # 1 | open | https://www.demoblaze.com/ | 
    self.driver.get("https://www.demoblaze.com/")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | id=itemc | 
    self.driver.find_element(By.ID, "itemc").click()
    # 4 | click | linkText=Laptops | 
    self.driver.find_element(By.LINK_TEXT, "Laptops").click()
    # 5 | click | linkText=Monitors | 
    self.driver.find_element(By.LINK_TEXT, "Monitors").click()
  
  def test_otherPages(self):
    # Test name: otherPages
    # Step # | name | target | value
    # 1 | open | https://www.demoblaze.com/ | 
    self.driver.get("https://www.demoblaze.com/")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | linkText=Contact | 
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    # 4 | click | css=#exampleModal span | 
    self.driver.find_element(By.CSS_SELECTOR, "#exampleModal span").click()
    # 5 | click | linkText=About us | 
    self.driver.find_element(By.LINK_TEXT, "About us").click()
    # 6 | click | css=#videoModal .modal-header span | 
    self.driver.find_element(By.CSS_SELECTOR, "#videoModal .modal-header span").click()
    # 7 | click | id=cartur | 
    self.driver.find_element(By.ID, "cartur").click()
    # 8 | click | id=login2 | 
    self.driver.find_element(By.ID, "login2").click()
    # 9 | click | css=#logInModal span | 
    self.driver.find_element(By.CSS_SELECTOR, "#logInModal span").click()
    # 10 | click | id=signin2 | 
    self.driver.find_element(By.ID, "signin2").click()
    # 11 | mouseOver | id=signin2 | 
    element = self.driver.find_element(By.ID, "signin2")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | mouseOut | id=signin2 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 13 | click | css=#signInModal span | 
    self.driver.find_element(By.CSS_SELECTOR, "#signInModal span").click()
  
  def test_removeFromCart(self):
    # Test name: removeFromCart
    # Step # | name | target | value
    # 1 | open | https://www.demoblaze.com/prod.html?idp_=4# | 
    self.driver.get("https://www.demoblaze.com/prod.html?idp_=4#")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | id=cartur | 
    self.driver.find_element(By.ID, "cartur").click()
    # 4 | click | linkText=Delete | 
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
  
  def test_signIn(self):
    # Test name: signIn
    # Step # | name | target | value
    # 1 | open | https://www.demoblaze.com/ | 
    self.driver.get("https://www.demoblaze.com/")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | id=login2 | 
    self.driver.find_element(By.ID, "login2").click()
    # 4 | click | css=#logInModal .form-group:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, "#logInModal .form-group:nth-child(1)").click()
    # 5 | click | id=loginusername | 
    self.driver.find_element(By.ID, "loginusername").click()
    # 6 | type | id=loginusername | adamf
    self.driver.find_element(By.ID, "loginusername").send_keys("adamf")
    # 7 | click | id=loginpassword | 
    self.driver.find_element(By.ID, "loginpassword").click()
    # 8 | type | id=loginpassword | adam
    self.driver.find_element(By.ID, "loginpassword").send_keys("adam")
    # 9 | click | css=#logInModal .btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, "#logInModal .btn-primary").click()
  
