# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHello():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hello(self):
    # Test name: hello
    # Step # | name | target | value
    # 1 | open | https://safatelli.github.io/tp-test-logiciel/assets/hello.html | 
    self.driver.get("https://safatelli.github.io/tp-test-logiciel/assets/hello.html")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 4 | type | id=username | adam
    self.driver.find_element(By.ID, "username").send_keys("adam")
    # 5 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 6 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 7 | type | id=username | lando
    self.driver.find_element(By.ID, "username").send_keys("lando")
    # 8 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 9 | assertText | id=message | Bonjour, lando !
    assert self.driver.find_element(By.ID, "message").text == "Bonjour, lando !"
  
